[tool.poetry]
name = "slack-integration"
version = "0.1.0"
description = ""
authors = ["Isidro López <islomar@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
slack-sdk = "^3.15.2"

[tool.poetry.dev-dependencies]
pytest = "^3.4"